server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toupiao?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        demo: debug

conf:
  rid: 76
  id: 4080
  minTime: 10000
  maxTime: 60000
  url: "https://4.hbcm666.cn//app/index.php?i=1&c=entry&id=%d&rid=%d&isopenlink=first&do=vote&m=tyzm_diamondvote&userss=&openid=%s"
  openIdUrl: "https://4.hbcm666.cn//app/index.php?i=1&c=entry&id=%d&rid=%d&isopenlink=first&do=viewc&m=tyzm_diamondvote&userss="
  ridUrl: "https://4.hbcm666.cn//app/index.php?i=1&c=entry&rid=1&isopenlink=first&do=indexx&m=tyzm_diamondvote&userss="
  playerUrl: "https://4.hbcm666.cn//app/index.php?i=1&c=entry&rid=%d&isopenlink=first&do=index&m=tyzm_diamondvote&userss="
  playerInfoUrl: "https://4.hbcm666.cn//app/index.php?i=1&c=entry&id=%d&rid=%d&isopenlink=first&do=view&m=tyzm_diamondvote&userss="
